#------------------------Local-------------------------------
spring.application.name=ProyectoGrupo4_GTICS
spring.datasource.url=jdbc:mysql://35.190.142.62:3306/proyectogtics
spring.datasource.username=root
spring.datasource.password=UY7_NR$Sl@YVib,J
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=syong7350@gmail.com
spring.mail.password=dezakdnxifvwvoaj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.hibernate.ddl-auto=none
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
#Cambiar por puerto 8080  para local
server.port=443
#Comentar si se corre proyecto de manera local
#---------------------------
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=
server.ssl.key-alias=tomcat
#----------------------------
#Aqui van las credenciales de dialogFlow
dialogflow.project.id=bot-nuevo-440622
dialogflow.agent.id=3dbc3f02-15c5-4c62-8e8c-778085345a16
dialogflow.location.id=global
dialogflow.language.code=es
#ESTOS PARAMETROS LOS PUEDES ENCONTRAR EN LAS RUTAS DE LAS PAGINAS DE DIALOG FLOW
